version: '3.8'

services:
  bot:
    build: .
    container_name: balance_transfer_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=/app/data/bot.db
      - LOG_FILE=/app/logs/bot.log
